### ISSUE TITLE
10.12.4 iso still results in errors on install ISO bootup

### ISSUE THREAD

**Issue by Ralnoc** [rtrouton/create_macos_vm_install_dmg#1]
Have you had any success using this script with 10.12.4? The README suggests you have, however when I tested it, I still end up with the `IOConsoleUsers: gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0` error.

If you were able to get a working ISO, where there any special actions you had to do for it to work?

**Comment by rtrouton** [comment]
I've tested the script with VMware Fusion 8.5.x and ESXi 6.5.x, and in both cases, both 10.12.4 and 10.12.5 installers worked. Are you using another virtualization solution?

**Comment by Ralnoc** [comment]
I've been using VirtualBox running on a Windows Host. I did finally get this to work, but it only worked on El Capitan and I have not been able to get it to update to Sierra or later.
