### ISSUE TITLE
Can't create iso image

### ISSUE THREAD

**Issue by mtissington** [rtrouton/create_macos_vm_install_dmg#10]
I can create the dmg great, but when trying to create the iso I get the following

`Do you also want an .iso disk image?
1) Yes
2) No
#? 1
-- Additional disk image will be created in .iso format. Proceeding...
-- macOS Installer application detected at the following path: /users/michael/desktop/install macOs Big Sur.app
-- Installer application for macOS 11.0.1 detected. Proceeding....
-- /users/michael/desktop/install macOs Big Sur.app/Contents/Resources/createinstallmedia tool detected. Proceeding....
-- Creating empty 15 GB disk image at the following location: /tmp/973D82DF-DF0B-4BCE-8469-CA80A1B5BF79.cdr
created: /tmp/973D82DF-DF0B-4BCE-8469-CA80A1B5BF79.cdr.dmg
-- Mounting disk image at /Volumes/973D82DF-DF0B-4BCE-8469-CA80A1B5BF79
/dev/disk2          	Apple_partition_scheme         	
/dev/disk2s1        	Apple_partition_map            	
/dev/disk2s2        	Apple_HFS                      	/Volumes/973D82DF-DF0B-4BCE-8469-CA80A1B5BF79
Erasing disk: 0%... 10%...
Error erasing disk error number (22, 0)
An error occurred erasing the disk.
-- Unmounting macOS installer disk image.
-- Converting macOS installer disk image to .iso format.
hdiutil: convert failed - Resource temporarily unavailable
mv: rename /users/michael/desktop/macOS_1101_installer.iso.cdr to /users/michael/desktop/macOS_1101_installer.iso: No such file or directory
-- Building process complete.
-- Built .dmg disk image file is available at /users/michael/desktop/macOS_1101_installer.dmg
-- Build failure! Built .iso disk image file not found! 
$ `

**Comment by kevinmcox** [comment]
@smashism has instructions for how to complete the ISO step manually on her blog here:
https://www.modtitan.com/2020/10/building-macos-big-sur-beta-vm-with.html

**Comment by tjluoma** [comment]
Those instructions didn’t work for me with the Big Sur official release.

**Comment by smashism** [comment]
@tjluoma I used that method to build a few VMs with the public release on Thursday and they worked just as they had before. (Just to add another data point to the conversation.)

Another guide popped up at https://travellingtechguy.blog/macos-big-sur-on-vmware-fusion-12/ that you can try.

**Comment by tjluoma** [comment]
Thanks @smashism I'm not sure what I did wrong before. I was getting a DMG/ISO but VMware said it has no operating system, or something like that.

The new process worked fine for me, and VMware 12 is currently making a Big Sur VM for me. Thank you again!

**Comment by Lotusshaney** [comment]
This problem appears to be because hdiutil does not support wildcards on detach and if the install app is from a DMG made with installinstallmacos.py the names of both images are the same.

I replaced the hdiutil at line 174 with this

installer_mounted_volume_mount="$(echo $installer_mounted_volume | cut -d / -f 1)"
ls /Volumes | grep -i "$installer_mounted_volume_mount" | while read ejectimage
do
	sudo hdiutil detach "/Volumes/$ejectimage" -force -quiet
done 

and that will step through and detach all disks.  Its a little crude but it works

This fix has been tested and works on 10.15.x and 11.0.1 Release

**Comment by smashism** [comment]
@Lotusshaney your update worked for me, thanks for sharing that.

**Comment by w0de** [comment]
@Lotusshaney your suggested fix worked for me - thank you. I suggest this is cleaner (as [one shouldn't parse ls](https://unix.stackexchange.com/questions/128985/why-not-parse-ls-and-what-to-do-instead), this is a glob job :D):

```
for volume in "/Volumes/$installer_mounted_volume"*; do
	sudo hdiutil detach "$volume" -force -quiet
done
```

**Comment by rtrouton** [comment]
Thanks for all the suggested fixes. I've incorporated @w0de 's approach as part of https://github.com/rtrouton/create_macos_vm_install_dmg/commit/e9a15da1c3aa5c5918bd3f72a3d5273d4ff9af84 .

**Comment by Lotusshaney** [comment]
This problem still happens on 11.2 OS and 11.2 from a mounter DMG made via installinstallmacos.py.

output from script is 

"-- Converting macOS installer disk image to .iso format.
hdiutil: convert failed - Resource temporarily unavailable"

Funnily enough my hacked code still works fine if used at line 174
