### ISSUE TITLE
Can't create iso image #10 is still a problem

### ISSUE THREAD

**Issue by Lotusshaney** [rtrouton/create_macos_vm_install_dmg#12]
Issue #10 is still a problem.

The problem still happens on 11.2 OS and 11.2 from a mounter DMG made via installinstallmacos.py.

output from script is

"-- Converting macOS installer disk image to .iso format.
hdiutil: convert failed - Resource temporarily unavailable"

Funnily enough my hacked code from Issue #10 still works fine if used at line 174

**Comment by MC1R-13** [comment]
Also happens on 11.3.1.  @Lotusshaney's fix still works.

**Comment by rtrouton** [comment]
Unable to reproduce.
