### ISSUE TITLE
Every macOS Version works EXCEPT 10.12.6 Sierra

### ISSUE THREAD

**Issue by gtrooper** [rtrouton/create_macos_vm_install_dmg#13]
Any news on this ? 10.12.6 refuses to even create the .dmg. Can I ask if there is any place to get a NEW 10.12.6 Installer ? Thanks for the AMAZING work !

**Comment by rtrouton** [comment]
Depending on the age of the 10.12.6 installer, it may be using a now-expired signing certificate. For more details on why that matters, please see the link below:

[https://tidbits.com/2019/10/28/redownload-archived-macos-installers-to-address-expired-certificates/](https://tidbits.com/2019/10/28/redownload-archived-macos-installers-to-address-expired-certificates/)

Apple has made macOS Sierra available for download via this KBase article:

[https://support.apple.com/kb/HT208202](https://support.apple.com/kb/HT208202)

**Comment by gtrooper** [comment]
> Depending on the age of the 10.12.6 installer, it may be using a now-expired signing certificate. For more details on why that matters, please see the link below:
> 
> https://tidbits.com/2019/10/28/redownload-archived-macos-installers-to-address-expired-certificates/
> 
> Apple has made macOS Sierra available for download via this KBase article:
> 
> https://support.apple.com/kb/HT208202

Yea I have already downloaded from exatcly the same source but I get the error. After I try to execute the script.. it STALLS and there is no progress. I tried to use Install macOS Sierra.app DIRECTLY using create install media command but it STILL STALLS, which shows that there seems to be something wrong with this specific installer. How could this be possible ? The installer comes directly from apple ..
