### ISSUE TITLE
Support for High Sierra

### ISSUE THREAD

**Issue by rhnorskov** [rtrouton/create_macos_vm_install_dmg#2]
Will you be adding support for High Sierra?

**Comment by seamusdemora** [comment]
Good question! But since it was asked  nearly 3 years ago - I guess it's safe to assume the answer is "No". Too bad - I hoped this would help me create a file that VMware can use to create a VM.

**Comment by rtrouton** [comment]
It’s always supported High Sierra. [Please see the README for supported installers](https://github.com/rtrouton/create_macos_vm_install_dmg/blob/master/README.md).

**Comment by seamusdemora** [comment]
Yeah - noticed that... but when I saw the open issue I wondered.

Thanks for closing the issue!
