### ISSUE TITLE
High Sierra: fails to create image for Sierra

### ISSUE THREAD

**Issue by madrobby** [rtrouton/create_macos_vm_install_dmg#3]
I'm trying to make a Sierra image on High Sierra. Fails with:

```
-- Creating empty read-write DMG located at /tmp/vmware-apple-basesystem-rw.EC5O.dmg..
created: /tmp/vmware-apple-basesystem-rw.EC5O.dmg
/dev/disk5          	Apple_partition_scheme         	
/dev/disk5s1        	Apple_partition_map            	
/dev/disk5s2        	Apple_HFS                      	/private/tmp/vmware-apple-basesystem.mYjZ
-- Restoring the BaseSystem to the read-write DMG using asr..
	Validating target...done
	Validating source...done
	Retrieving scan information...done
	Validating sizes...done
	Restoring  ....10....20....30....40....50....60....70....80....90....100
	Remounting target volume...done
umount(/Volumes/OS X Base System): Resource busy -- try 'diskutil unmount'
hdiutil: attach failed - Resource busy
rm: /tmp/vmware-apple-basesystem.mYjZ/System/Installation/Packages: No such file or directory
-- Moving 'Packages' directory from the ESD to BaseSystem..
```

**Comment by madrobby** [comment]
(Same thing happened with a 10.11 Installer image.)

**Comment by markwatson** [comment]
Too lazy to do a PR right now, but the issue is that `BaseSystem.dmg` isn't copied over. You need two additional lines:

```
72d71
< 		BASE_SYSTEM_DMG="$ESD/Contents/SharedSupport/BaseSystem.dmg"
122d120
<  cp "$BASE_SYSTEM_DMG" $MNT_ESD
```

Then pass in the install app as an argument, and you're off to the races.

**Comment by jyounus** [comment]
Where would I put these lines inside of the script?

**Comment by jmartinFT** [comment]
@jyounus you would put these items between 71 and 72  and then between 120 and 121 

I used the whole snippet of the portion of code, looking like this:

if [ -d "$ESD" ]; then
	# we might be an install .app
	if [ -e "$ESD/Contents/SharedSupport/InstallESD.dmg" ]; then
        BASE_SYSTEM_DMG="$ESD/Contents/SharedSupport/BaseSystem.dmg"
		ESD="$ESD/Contents/SharedSupport/InstallESD.dmg"
        else
		msg_error "Can't locate an InstallESD.dmg in this source location $ESD!"
	fi
fi

msg_status "Mounting BaseSystem.."
    cp "$BASE_SYSTEM_DMG" $MNT_ESD
BASE_SYSTEM_DMG="$MNT_ESD/BaseSystem.dmg"
MNT_BASE_SYSTEM=$(/usr/bin/mktemp -d /tmp/vmware-apple-basesystem.XXXX)
[ ! -e "$BASE_SYSTEM_DMG" ] && msg_error "Could not find BaseSystem.dmg in $MNT_ESD"
hdiutil attach "$BASE_SYSTEM_DMG" -mountpoint "$MNT_BASE_SYSTEM" -nobrowse -owners on
if [ $? -ne 0 ]; then
    msg_error "Could not mount $BASE_SYSTEM_DMG on $MNT_BASE_SYSTEM"
    exit 1
fi

**Comment by daem0ndev** [comment]
@markwatson @jmartinFT is there any unforseen issues with this fix? if not, i dont mind submitting the PR :)

**Comment by gnowland** [comment]
Running this patch on macOS 10.12.6 for a "Install macOS High Sierra.app" results in a .dmg that gives me a grey screen in VMware Fusion 10...

**Comment by markwatson** [comment]
@daem0ndev I'm not sure, I couldn't figure out how to actually get the install to complete so eventually just gave up 😹 . It's been a while, but I think I got the same issue that @gnowland just mentioned.

**Comment by gnowland** [comment]
@markwatson @daem0ndev I ended up just following the steps in "Step One" on this guide and it worked, really simple: https://www.howtogeek.com/289594/how-to-install-macos-sierra-in-virtualbox-on-windows-10/

**Comment by robertluwang** [comment]
does it support macOS 10.14 Mojave ?
