### ISSUE TITLE
Issue when creating an iso 

### ISSUE THREAD

**Issue by binnythomas-1989** [rtrouton/create_macos_vm_install_dmg#6]
**Build failure! Built .iso disk image file not found!**
hdiutil convert macOS_10153_installer.dmg -format UDTO -o macOS_10153_installer.iso
hdiutil: convert failed - Resource temporarily unavailable

Issue on the script with the latest version.

On version of  MACOS Catalina the script fails with the error above

Please find the fix below

`# Move and rename the installer disk image to match the following standard:`
`#`
`# macOS_[OS Version Number Here]_installer`

`mv /tmp/"$random_disk_image_name".cdr.dmg "$output_directory"/macOS_"$installer_version_digits_only"_installer.dmg
msg_status "Unmounting macOS installer disk image."`

`hdiutil detach "/Volumes/$installer_mounted_volume"
retVal=$?
if [ $retVal -ne 0 ]; then
    diskutil eject "/Volumes/$installer_mounted_volume"
fi`

**Comment by binnythomas-1989** [comment]
I dont have access to create a pull request, was having issues when i tried. Please merge the changes if you see its valid.

**Comment by rtrouton** [comment]
Unable to reproduce problem. Script is able to produce .iso files fine as of macOS 10.15.5.
