### ISSUE TITLE
No issues - just feedback

### ISSUE THREAD

**Issue by seamusdemora** [rtrouton/create_macos_vm_install_dmg#7]
Hello @rtrouton 

Just wanted to say thanks for this - `create_macos_vm_install_dmg` 

I [struggled for days](https://apple.stackexchange.com/questions/393753/creating-high-sierra-as-vm-under-vmware-fusion/393978#393978) trying to do this - to create a High Sierra VM under VMware Fusion 11.5.5 on Catalina 10.15.5. The best I was able to do was a 'work-around': creating the VM on an old Mac & VMware Fusion & importing that VM to my Catalina system. 

I found & bookmarked your repo while in the middle of another attempt (that eventually failed), and decided to try it earlier today. It was instantly successful. FWIW, I'm going to write this up as an additional "answer" to my Q on SE. I wish I had tried this first - but then I wouldn't appreciate you nearly as much! LOL

In closing, your script needs more publicity. A few words in a wiki explaining the "problem", and how this overcomes the issue might help. Anyway - thanks again! 

<img width="1136" alt="Screen Shot 2020-06-16 at 4 44 47 AM" src="https://user-images.githubusercontent.com/14911811/84762449-70275a00-af90-11ea-8a2f-f3d400a1757b.png">

**Comment by rtrouton** [comment]
You're welcome! I'm glad to hear it helped you out.
