### ISSUE TITLE
Failing to recognize MacOS 11.0 beta 3

### ISSUE THREAD

**Issue by Tribruin** [rtrouton/create_macos_vm_install_dmg#8]
Apple has changed the xml file with Big Sur beta 3 and is reporting 11.0 instead of 10.16. This is causing the OS check line 110 to fail. I added a secondary check and it seems to work. 

`if [[ "$installer_qualifies" -lt 1012 ]] && [[ $macOS11 -eq 0 ]]; then`

Edit: I just checked the dmg and realized it was empty. I am getting an error when trying to mount empty disk image:
`hdiutil: attach failed - Resource busy
/Volumes/C1EF3958-1C88-47F1-809D-346D1950BFB7 is not a valid volume mount point.`

**Comment by rtrouton** [comment]
Updated script to address both the OS and disk sizing issues.
